const os = require('os');
const fs = require('fs');
const path = require('path');

const interfaces = os.networkInterfaces();
let bestIp = '10.0.2.2'; // Default emulator fallback

// Find the first external IPv4 address
for (const name of Object.keys(interfaces)) {
    for (const info of interfaces[name]) {
        if (!info.internal && info.family === 'IPv4') {
            if (info.address.startsWith('192.168.') || info.address.startsWith('10.')) {
                 bestIp = info.address;
            }
        }
    }
}

const envContent = `# [Auto-generated by setup-env.js]
# Run 'npm run setup:env' to regenerate this file if your IP changes.

EXPO_PUBLIC_USER_SERVICE_URL=http://${bestIp}:3001
EXPO_PUBLIC_POST_SERVICE_URL=http://${bestIp}:3002
EXPO_PUBLIC_POINTS_SERVICE_URL=http://${bestIp}:3003
EXPO_PUBLIC_PAYMENT_SERVICE_URL=http://${bestIp}:3004
`;

const envPath = path.join(__dirname, '../.env.local');
fs.writeFileSync(envPath, envContent);

console.log(`\n===========================================`);
console.log(`✅ EXPO NETWORK CONFIGURATION SET`);
console.log(`➡️  Local Network IP detected as: ${bestIp}`);
console.log(`➡️  Created/Updated: .env.local`);
console.log(`===========================================\n`);
